CREATE TABLE [dbo].[Persons]
(
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[SSN] INT UNIQUE, 
	[Name] NVARCHAR(300) NOT NULL,
	[Born] DATETIME NOT NULL,
	[State] BIT NOT NULL,
	[File] VARBINARY(MAX) NULL,
	[CreateDate] DATETIME NOT NULL,
	[UpdateDate] DATETIME NULL
)
